### ISSUE TITLE
Students Analyse des Génomes - 9 décembre 2019

### ISSUE THREAD

**Issue by drosofff** [ARTbio/Run-Galaxy#24]
### please, check your access to Google resources coupon with your email address listed below.
Whatever it is successful or not, report your case as an individual comment in this issue (not in this section that you cannot edit, in additional comments below this one)

- [x] Julie	AUTAA	julie(dot)autaa(at)etu(dot)sorbonne-universite(dot)fr
- [x] Dounia	CHATER	dounia(dot)chater(at)etu(dot)sorbonne-universite(dot)fr
- [x] Axel	DE BERNARDI	axel(dot)de_bernardi(at)etu(dot)upmc(dot)fr
- [x] Maxime	HEINTZÉ	maxime(dot)heintze(at)etu(dot)upmc(dot)fr
- [ ] Achille	JULIENNE	achille(dot)julienne(at)etu(dot)sorbonne-universite(dot)fr
- [x] Léa	MENEU	lea(dot)meneu(at)etu(dot)sorbonne-universite(dot) fr
- [x] Annabelle	WURMSER	annabelle(dot)wurmser(at)ens(dot)fr
- [x] Philippe	COUVERT	philippe(dot)couvert(at)sorbonne-universite(dot)fr
- [x] Maud	GITS-MUSELLI	maud(dot)gits(at)etu(dot)univ-paris-diderot(dot)fr
- [x] Mélanie	MAGNAN	melanie(dot)magnan(at)inserm(dot)fr
- [x] Victor	BILLON	victor(dot)billon(at)ens-cachan(dot)fr
- [x] Lina-Marie	BRIU	lina-marie(dot)briu(at)etu(dot)univ-paris-diderot(dot)fr
- [x] Violette	CHARTEAU	violette(dot)charteau(at)etu(dot)univ-paris-diderot(dot)fr
- [x] Alice	COPIN	alice(dot)copin(at)etu(dot)univ-paris-diderot(dot)fr
- [x] Giulia	FANTOZZI	giulia(dot)fantozzi(at)studenti(dot)unipd(dot)it
- [ ] Abderaouf	HAMZA	hz05688(at)etu(dot)parisdescartes(dot)fr
- [ ] Romain	NICOLLE	 romain(dot)nicolle(at)etu(dot)univ-paris-diderot(dot)fr
- [x] Alexandre	PERRIER	alexandre(dot)perrier1(at)etu(dot)parisdescartes(dot)fr
- [ ] Lucie	PIERRON	lucie(dot)pierron(at)etu(dot)parisdescartes(dot)fr
- [x] Camille	VEREBI	camille(dot)verebi(at)etu(dot)parisdescartes(dot)fr

**Comment by cverebi** [comment]
Camille VEREBI camille(dot)verebi(at)etu(dot)parisdescartes(dot)FR : code and redeem done, no issues.

**Comment by PCouvert** [comment]
Philippe Couvert. Pas de problème.

**Comment by quark13** [comment]
Ok pour moi aussi ! 
Alexandre PERRIER _alexandre(dot)perrier1(at)etu(dot)parisdescartes(dot)fr_

**Comment by maud9** [comment]
ok pour moi :)

**Comment by AliceCopin** [comment]
Bon pour moi aussi !

**Comment by julotta** [comment]
Moi aussi !

**Comment by Giulia-fa** [comment]
ok pour moi aussi

**Comment by violette-charteau** [comment]
28min44 Londres

**Comment by lmeneu** [comment]
Ok pour moi !

**Comment by MaximeHntz** [comment]
Bon pour moi !

**Comment by Victordu27** [comment]
All good

**Comment by drosofff** [comment]
This is a GitHub Party ? 🥇

**Comment by c-dounia** [comment]
enfin fini avec l'inscription

**Comment by chiloux** [comment]
Salut je suis là !

**Comment by Annabelle-IME** [comment]
https://lesjoiesducode.fr/page/2

**Comment by MelanieMagnan** [comment]
C'est bon pour moi

**Comment by axeldB** [comment]
Fait.

**Comment by Lmbriu** [comment]
C'est bon aussi.

**Comment by drosofff** [comment]
@Annabelle-IME cela veut dire que l'inscription à fonctionné, ou qu'elle n'a pas fonctionné ?

**Comment by drosofff** [comment]
même question à @chiloux alias Achille JULIENNE je suppose ? :alien:

**Comment by Annabelle-IME** [comment]
C'est bon!

**Comment by Xamonir** [comment]
3,141592653589793238462643383279502884

**Comment by Xamonir** [comment]
j'avais mis un commentaire il me semble

**Comment by Xamonir** [comment]
Pourquoi donc ARTbio avait supprimé mon commentaire ?
je tente de le remettre

3.141592653589793238462643383279502884

**Comment by Victordu27** [comment]
flooder

**Comment by Annabelle-IME** [comment]
real    30m28.739s
user    9m54.023s
sys     1m37.512s

**Comment by Victordu27** [comment]
real    30m16.914s
user    9m46.488s
sys     1m36.486s

**Comment by c-dounia** [comment]
real    29m5.226s
user    10m1.209s
sys     1m42.115s

**Comment by Luciep300** [comment]
Iowa je crois

real    30m10.293s
user    11m36.374s
sys     1m54.189s
