### ISSUE TITLE
The ultimate Pasteur 2019 Ansible Racing

### ISSUE THREAD

**Issue by drosofff** [ARTbio/Run-Galaxy#25]
Please Every Participant is invited to report the time of his/her Ansible Galaxy deployment, in the form of:
```
real	10m27.142s
user	8m22.941s
sys	1m16.409s
```
Do not fake your results, it is easy to check :-)

## There will be prices for the winners !!

- An interrupted deployment is disqualifying...

**Comment by lmeneu** [comment]
real    25m21.608s
user    9m5.868s
sys     1m27.826s


Zone : Iowa - us-central1-a

**Comment by julotta** [comment]
real    25m58.523s
user    9m7.375s
sys     1m29.584s

us-central1-a

**Comment by PCouvert** [comment]
Iowa
real    25m51.096s
user    9m5.009s
sys     1m27.821s

**Comment by cverebi** [comment]
real    26m16.537s
user    9m6.518s
sys     1m31.189s
Iowa :'(

**Comment by MaximeHntz** [comment]
real    26m41.236s
user    9m9.552s
sys     1m29.731s

Iowa : us-central1-a

**Comment by Giulia-fa** [comment]
real    27m2.488s
user    9m1.756s
sys     1m30.033s

**Comment by axeldB** [comment]
real    30m5.847s
user    9m16.365s
sys     1m31.975s

**Comment by Xamonir** [comment]
real    29m46.289s
user    11m7.024s
sys     1m52.570s
iowa

**Comment by maud9** [comment]
real    29m27.895s
user    9m35.016s
sys     1m35.431s

West europe Pays bas

**Comment by chiloux** [comment]
real    29m28.885s
user    9m24.030s
sys     1m32.579s

**Comment by quark13** [comment]
real    29m13.027s
user    9m5.126s
sys     1m29.292s
London

**Comment by axeldB** [comment]
> real 30m5.847s
> user 9m16.365s
> sys 1m31.975s
Pays-Bas

**Comment by MelanieMagnan** [comment]
real    28m51.358s
user    9m25.947s
sys     1m32.176s
London

**Comment by Annabelle-IME** [comment]
real 30m28.739s
user 9m54.023s
sys 1m37.512s

Pays-Bas <3

**Comment by chiloux** [comment]
real    29m28.885s
user    9m24.030s
sys     1m32.579s

Pays-Bas

**Comment by Victordu27** [comment]
Pays Bas ........
real    30m16.914s
user    9m46.488s
sys     1m36.486s

**Comment by Oufra** [comment]
real    26m15.710s
user    9m41.936s
sys     1m32.587s
Londres

**Comment by Luciep300** [comment]
real    30m10.293s
user    11m36.374s
sys     1m54.189s

Iowa je crois

**Comment by Lmbriu** [comment]
real    26m41.958s
user    10m59.724s
sys     1m50.864s

Iowa

**Comment by c-dounia** [comment]
real    29m5.226s
user    10m1.209s
sys     1m42.115s

pays-bas

**Comment by violette-charteau** [comment]
real    28m44.008s
user    9m5.544s
sys     1m30.146s

Londres

**Comment by AliceCopin** [comment]
real    26m10.326s
user    9m6.654s
sys     1m29.310s

Iowa

**Comment by drosofff** [comment]
And here are the results on the ansible race (values converted in seconds)

## Winner: @lmeneu  (1521.608s)
### 2nd price: @PCouvert (1551.096s)
#### 3rd price: @julotta (1558.523s)

And all data with a clear correlation with area:

zone | variable | value
-- | -- | --
Iowa | real | 1521.608
Iowa | real | 1551.096
Iowa | real | 1558.523
Iowa | real | 1570.326
London | real | 1575.71
Iowa | real | 1576.537
Iowa | real | 1601.236
Iowa | real | 1601.958
Iowa | real | 1622.488
London | real | 1724.008
London | real | 1731.358
Pays-Bas | real | 1745.226
London | real | 1753.027
Pays-Bas | real | 1767.895
Pays-Bas | real | 1768.885
Iowa | real | 1786.289
Pays-Bas | real | 1805.847
Iowa | real | 1810.293
Pays-Bas | real | 1816.914
Pays-Bas | real | 1828.739

![Rplot](https://user-images.githubusercontent.com/11705625/70581861-e9e12400-1bb8-11ea-94a3-0a1f1cf78fc2.png)

**Comment by drosofff** [comment]
@lmeneu @julotta @PCouvert Official winners of the race. Tell your friends !
