### ISSUE TITLE
Students "Biologie des génomes" Décembre 2018

### ISSUE THREAD

**Issue by drosofff** [ARTbio/Run-Galaxy#4]
1. **Mlle	Manuela	BAQUERO PEREZ	SU	manuela [dot] baquero [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

2. **Mlle	Lisa	BAREL	SU	lisajm [dot] barel [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

3. **M.	Amaury	BIGNAUD	PSL	amaury [dot] bignaud [at] ens [dot] fr**
- [x] Gmail address
- [x] GCE Activated and Tested

4. **Mme	Laurianne	BLUKACZ	Paris Diderot	lblukacz [at] outlook [dot] fr**
- [x] Gmail address
- [x] GCE Activated and Tested

5. **Mme	Marie	BOISSON	Paris Diderot	boisson [dot] marie [at] gmail [dot] com**
- [x] Gmail address
- [ ] GCE Activated and Tested

6. **Mme	Agathe	BOUSSAROQUE	Paris Diderot	agathe [dot] boussaroque [at] yahoo [dot] fr**
- [ ] Gmail address
- [x] GCE Activated and Tested

7. **M.	Emmanuel	CAZOTTES	Paris Diderot	cazottes [dot] emmanuel [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

8. **Mlle	Olivia	CHARMANT	SU	olivia [dot] charmant [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

9. **M.	Florent	CHARTON	Paris Diderot	florent [dot] charton [dot] apb [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

10. **M.	Raphaël	CHEVALIER	Paris Sud	raphael [dot] chevalier [at] u-psud [dot] fr**
- [x] Gmail address
- [x] GCE Activated and Tested

11. **M.	Florian	CONSTANTY	Paris Diderot	flo [dot] constanty [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

12. **M.	Abdelhamid	DERIET AMAR TOUIL	Réseau IP Alger	deriet [dot] abdelhamid [at] gmail [dot] com**
- [x] Gmail address
- [x] _Biosphere_

13. **M.	Antoine	DESPINASSE	SU	antoine [dot] despinasse [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

14. **Mme	Alice	GRANADOS	Paris Diderot	alice [dot] granados [dot] 4 [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

15. **M.	Alexis	HARDY	Paris Diderot	alexydrah [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

16. **Mlle	Jeanne	MATTEI	SU	jeanne [dot] mattei [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

17. **Mme	Pauline	MONIN	Paris Diderot	pauline [dot] monin [at] hotmail [dot] fr**
- [x] Gmail address
- [x] GCE Activated and Tested

18. **Mlle	Salomé	NASHED	SU	s [dot] nashed [at] free [dot] fr**
- [ ] Gmail address
- [ ] GCE Activated and Tested

19. **Mlle	Andrea	ROSSI	SU	rossi3e7g2 [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

20. **Mme	Marine	TESSARECH	Paris Diderot	marine [dot] tessarech [at] gmail [dot] com**
- [x] Gmail address
- [x] GCE Activated and Tested

**Comment by drosofff** [comment]
@everyone interested: Indeed it is not possible to edit my issue, therefore impossible to check the boxes. However, if you read this comment, you can just in turn add a new comment in this thread specifying your name and your status with regard to the 2 assigned tasks for the training.
Thanks !

**Comment by manuelabaquero** [comment]
Manuela	BAQUERO PEREZ	SU	manuela [dot] baquero [at] gmail [dot] com

- [x] Gmail address

- [x] GCE Activated and Tested

**Comment by AgatheBoussaroque** [comment]
Agathe Boussaroque ; Gmail address, GCE Activated and Tested

**Comment by drosofff** [comment]
@AgatheBoussaroque Could you give me the gmail address...

**Comment by AlGranados** [comment]
Alice Granados; gmail : alice.granados.4@gmail.com, GCE activated and tested

**Comment by ABignaud** [comment]
M. Amaury BIGNAUD :

Gmail address : amauryb.87@gmail.com
GCE Activated and Tested

**Comment by JeanneMattei** [comment]
Jeanne Mattei :
gmail : jeanne.mattei@gmail.com 
GCE activated and tested

**Comment by MarineTessa** [comment]
Marine Tessarech 
Gmail : marine.tessarech@gmail.com
GCE activated and tested

**Comment by oliviacharmant** [comment]
Olivia Charmant 
gmail : olivia.charmant@gmail.com
GCE activated and tested

**Comment by ljmbarel** [comment]
Lisa Barel
gmail: lisajm.barel@gmail.com
GCE activated and tested
